# Generated by Django 4.1.3 on 2022-11-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentiacation', '0002_remove_user_is_active_remove_user_is_staff'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
